// di76 - by Dwight Ivany
// Sound-equivalent simplified code of the Stillwell 1175 compressor JSFX
// by Thomas Scott Stillwell. Output is identical to di76/the 1175 normal
// modes; dead code and no-op variables have been removed.
// Slots 1,5,9,13,17,21 are the real controls; "-reserved" spacers between
// them are expansion room - new sliders replace a spacer in place, never
// renumber slots (REAPER saves slider values positionally).
// Original source: https://github.com/stillwellaudio/jsfx/blob/master/1175
// The copyright notice, license conditions and disclaimer below are retained
// verbatim from the original source (BSD license).

// Copyright 2006, Thomas Scott Stillwell
// All rights reserved.
//
//Redistribution and use in source and binary forms, with or without modification, are permitted 
//provided that the following conditions are met:
//
//Redistributions of source code must retain the above copyright notice, this list of conditions 
//and the following disclaimer. 
//
//Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
//and the following disclaimer in the documentation and/or other materials provided with the distribution. 
//
//The name of Thomas Scott Stillwell may not be used to endorse or 
//promote products derived from this software without specific prior written permission. 
//
//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR 
//IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
//FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS 
//BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
//PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
//STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
//THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

desc:di76 Compressor (Dwight) [sound-equivalent simplified 1175]
desc:di76 FAST Attack Compressor
//tags: dynamics compressor
//author: Stillwell (original 1175), Dwight Ivany (di76)

slider1:0<0,400,20>High Pass (Hz, 0 = off)
slider2:0<0,1,1>-reserved
slider3:0<0,1,1>-reserved
slider4:0<0,1,1>-reserved
slider5:0<-60,0,0.1>Threshold (dB)
slider6:0<0,1,1>-reserved
slider7:0<0,1,1>-reserved
slider8:0<0,1,1>-reserved
slider9:4<4,100,1>Ratio
slider10:0<0,1,1>-reserved
slider11:0<0,1,1>-reserved
slider12:0<0,1,1>-reserved
slider13:0<-20,20,0.1>Gain (dB)
slider14:0<0,1,1>-reserved
slider15:0<0,1,1>-reserved
slider16:0<0,1,1>-reserved
slider17:20<20,2000,10>Attack (uS)
slider18:0<0,1,1>-reserved
slider19:0<0,1,1>-reserved
slider20:0<0,1,1>-reserved
slider21:250<20,1000,1>Release (mS)

in_pin:left input
in_pin:right input
out_pin:left output
out_pin:right output

@init
  log2db = 8.6858896380650365530225783783321; // 20 / ln(10)
  db2log = 0.11512925464970228420089957273422; // ln(10) / 20
  gr_meter = 1;
  gr_meter_decay = exp(1/(1*srate));

@slider
  hpcutoff = slider1;
  hpb1 = exp(-4*$pi * hpcutoff / srate);
  hpa0 = (hpb1 + 1) * 0.5;

  thresh = slider5;
  threshv = exp(thresh * db2log);

  ratio = slider9 < 6 ? 4 : slider9 < 10 ? 8 : slider9 < 16 ? 12 : slider9 < 60 ? 20 : 100;
  slider9 = ratio;
  makeup = slider13;
  makeupv = exp(makeup * db2log);
  atcoef = exp(-1/((slider17/1000000) * srate));
  relcoef = exp(-1/((slider21/1000) * srate));

@sample
  slider1 > 0 ? (
    hp0 = (spl0 - old_spl0) * hpa0 + hp0 * hpb1;
    hp1 = (spl1 - old_spl1) * hpa0 + hp1 * hpb1;
    old_spl0 = spl0;
    old_spl1 = spl1;
    spl0 = hp0;
    spl1 = hp1;
  );

  det = max(abs(spl0), abs(spl1));

  overdb = max(0, log2db * log(det/threshv));

  overdb > rundb ? (
    rundb = overdb + atcoef * (rundb - overdb);
  ) : (
    rundb = overdb + relcoef * (rundb - overdb);
  );
  overdb = rundb;

  grv = exp(-overdb * (ratio-1)/ratio * db2log);

  grv < gr_meter ? gr_meter=grv : ( gr_meter*=gr_meter_decay; gr_meter>1?gr_meter=1; );

  spl0 *= grv * makeupv;
  spl1 *= grv * makeupv;


@gfx 0 32 // request horizontal/vertical heights (0 means dont care)

  gr_meter *= exp(1/30); gr_meter>1?gr_meter=1; // decay meter here so if the audio processing stops it doesnt "stick"
  gfx_r=1; gfx_g=gfx_b=0; gfx_a=0.8;

  meter_bot=20;
  meter_h=min(gfx_h,32);
  xscale=gfx_w*20/meter_bot;

  gfx_y=0;
  gfx_x=gfx_w + log10(gr_meter)*xscale;
  gfx_rectto(gfx_w,meter_h);

  gfx_r=gfx_g=gfx_b=1.0; gfx_a=0.6;

  s2=sqrt(2)/2;
  g = s2;
  while(
    gfx_x=gfx_w + log10(g)*xscale;
    gfx_x >= 0 ? 
    (
      gfx_y=0;
      gfx_lineto(gfx_x,meter_h,0);
      gfx_y=meter_h-gfx_texth;
      gfx_x+=2;
      gfx_drawnumber(log10(g)*20,0);
      gfx_drawchar($'d');
      gfx_drawchar($'B');
    );
    g*=s2;
    gfx_x >=0;
  );
  gfx_a=1;

  gfx_x=0; gfx_y=meter_h/2 - gfx_texth/2;
  gfx_drawnumber(log10(gr_meter)*20,1);
  gfx_drawchar($'d');
  gfx_drawchar($'B');
